apiVersion: v1
kind: Secret
metadata:
  name: monitoring-auth
  namespace: qatra
type: Opaque
stringData:
  auth: |
    salim:{SHA}SEa4tjjlcfD3xR78V2y0v0Uny/g=
    admin:{SHA}0DPiKuNIrr5DUM/zqzigLKa4gaY=
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: monitoring-basic-auth
  namespace: qatra
spec:
  basicAuth:
    secret: monitoring-auth
    removeHeader: true
